import { Home, Users, File, Stars, Settings } from "lucide-react";

export const NAME_PROJECT = "Apc Prime";

export const ROUTES = [
  {
    title: "Home",
    url: "/",
    items: [],
    icon: Home,
  },
  {
    title: "Users",
    url: "/users",
    items: [],
    icon: Users,
  },
  {
    title: "Requests",
    url: "/requests",
    items: [],
    icon: File,
  },
  {
    title: "Transactions",
    url: "/transactions",
    icon: File,
    items: [
      {
        title: "Pending",
        url: "/pending",
      },
      {
        title: "Accepted",
        url: "/accepted",
      },
      {
        title: "Rejected",
        url: "/rejected",
      },
    ],
  },
  {
    title: "Kyc files",
    url: "/kyc-files",
    items: [],
    icon: Stars,
  },
  {
    title: "Settings",
    url: "/settings",
    items: [],
    icon: Settings,
  },
];

export // Mock data for demonstration
const mockUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    phone: "+1234567890",
    accountManager: "Alice Smith",
    status: "active" as const,
    role: "admin" as const,
    telegram: "@johndoe",
    tradingAccounts: ["acc1", "acc2"],
    wallets: ["0x123..."],
    country: "USA",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "+1987654321",
    accountManager: "Bob Johnson",
    status: "inactive" as const,
    role: "user" as const,
    telegram: "@janesmith",
    tradingAccounts: ["acc3"],
    wallets: ["0x456..."],
    country: "Canada",
    createdAt: new Date("2023-03-22"),
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@example.com",
    phone: "+1122334455",
    accountManager: "Carol Davis",
    status: "blocked" as const,
    role: "manager" as const,
    telegram: "@mikej",
    tradingAccounts: [],
    wallets: ["0x789..."],
    country: "UK",
    createdAt: new Date("2023-05-08"),
  },
  {
    id: "4",
    name: "Sarah Williams",
    email: "sarah@example.com",
    phone: "+1556677889",
    accountManager: "David Wilson",
    status: "pending" as const,
    role: "user" as const,
    telegram: "@sarahw",
    tradingAccounts: ["acc4", "acc5"],
    wallets: [],
    country: "Australia",
    createdAt: new Date("2023-06-14"),
  },
  {
    id: "5",
    name: "Alex Brown",
    email: "alex@example.com",
    phone: "+1778899001",
    accountManager: "Emma Lee",
    status: "active" as const,
    role: "user" as const,
    telegram: "@alexb",
    tradingAccounts: ["acc6"],
    wallets: ["0xabc..."],
    country: "Germany",
    createdAt: new Date("2023-07-20"),
  },
  {
    id: "6",
    name: "Michael Brown",
    email: "michael@example.com",
    phone: "+1889900112",
    accountManager: "Fiona Chen",
    status: "active" as const,
    role: "user" as const,
    telegram: "@michaelb",
    tradingAccounts: ["acc7"],
    wallets: ["0xdef..."],
    country: "France",
    createdAt: new Date("2023-08-25"),
  },
  {
    id: "7",
    name: "Olivia Davis",
    email: "olivia@example.com",
    phone: "+1990011223",
    accountManager: "George White",
    status: "pending" as const,
    role: "user" as const,
    telegram: "@oliviad",
    tradingAccounts: [],
    wallets: ["0xghi..."],
    country: "Spain",
    createdAt: new Date("2023-09-30"),
  },
  {
    id: "8",
    name: "William Taylor",
    email: "william@example.com",
    phone: "+1234567890",
    accountManager: "Henry Smith",
    status: "active" as const,
    role: "user" as const,
    telegram: "@willt",
    tradingAccounts: ["acc8", "acc9"],
    wallets: ["0xjkl..."],
    country: "Canada",
    createdAt: new Date("2023-10-05"),
  },
  {
    id: "9",
    name: "Sophia Martinez",
    email: "sophia@example.com",
    phone: "+1345678901",
    accountManager: "Isabella Wang",
    status: "blocked" as const,
    role: "user" as const,
    telegram: "@sophiam",
    tradingAccounts: ["acc9"],
    wallets: ["0xmno..."],
    country: "Mexico",
    createdAt: new Date("2023-10-12"),
  },
  {
    id: "10",
    name: "James Wilson",
    email: "james@example.com",
    phone: "+1456789012",
    accountManager: "Jack Brown",
    status: "pending" as const,
    role: "user" as const,
    telegram: "@jamesw",
    tradingAccounts: [],
    wallets: ["0xpqr..."],
    country: "UK",
    createdAt: new Date("2023-10-20"),
  },
  {
    id: "11",
    name: "Emma Anderson",
    email: "emma@example.com",
    phone: "+1567890123",
    accountManager: "Kevin Lee",
    status: "active" as const,
    role: "user" as const,
    telegram: "@emmaa",
    tradingAccounts: ["acc10"],
    wallets: ["0xstu..."],
    country: "Ireland",
    createdAt: new Date("2023-10-25"),
  },
  {
    id: "12",
    name: "Lucas Garcia",
    email: "lucas@example.com",
    phone: "+1678901234",
    accountManager: "Lily Chen",
    status: "inactive" as const,
    role: "user" as const,
    telegram: "@lucasg",
    tradingAccounts: ["acc11"],
    wallets: [],
    country: "Brazil",
    createdAt: new Date("2023-11-01"),
  },
  {
    id: "13",
    name: "Ava Thompson",
    email: "ava@example.com",
    phone: "+1789012345",
    accountManager: "Mason White",
    status: "active" as const,
    role: "user" as const,
    telegram: "@avat",
    tradingAccounts: ["acc12"],
    wallets: ["0xvwx..."],
    country: "Australia",
    createdAt: new Date("2023-11-08"),
  },
  {
    id: "14",
    name: "Ethan Rodriguez",
    email: "ethan@example.com",
    phone: "+1890123456",
    accountManager: "Noah Davis",
    status: "pending" as const,
    role: "user" as const,
    telegram: "@ethanr",
    tradingAccounts: ["acc13"],
    wallets: ["0xyz..."],
    country: "Argentina",
    createdAt: new Date("2023-11-15"),
  },
  {
    id: "15",
    name: "Isabella Lee",
    email: "isabella@example.com",
    phone: "+1901234567",
    accountManager: "Oliver Smith",
    status: "active" as const,
    role: "user" as const,
    telegram: "@isabellal",
    tradingAccounts: ["acc14"],
    wallets: ["0xaaa..."],
    country: "Italy",
    createdAt: new Date("2023-11-22"),
  },
  {
    id: "16",
    name: "Mason Clark",
    email: "mason@example.com",
    phone: "+2012345678",
    accountManager: "Parker Wilson",
    status: "blocked" as const,
    role: "user" as const,
    telegram: "@masonc",
    tradingAccounts: ["acc15"],
    wallets: ["0xbbb..."],
    country: "Sweden",
    createdAt: new Date("2023-11-29"),
  },
  {
    id: "17",
    name: "Charlotte White",
    email: "charlotte@example.com",
    phone: "+2123456789",
    accountManager: "Quinn Brown",
    status: "active" as const,
    role: "user" as const,
    telegram: "@charlottew",
    tradingAccounts: ["acc16"],
    wallets: ["0xccc..."],
    country: "Norway",
    createdAt: new Date("2023-12-05"),
  },
];

export const mockRequests = [
  {
    id: "REQ-001",
    name: "John Doe",
    email: "john@example.com",
    phone: "+1234567890",
    accountNumber: "A00123456",
    operationType: "create-account",
    status: "pending" as const,
    accountManager: "Alice Smith",
    rejectionReason: null,
    requestDate: new Date("2023-11-15"),
  },
  {
    id: "REQ-002",
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "+1987654321",
    accountNumber: "A00987654",
    operationType: "change-password",
    status: "approved" as const,
    accountManager: "Bob Johnson",
    rejectionReason: null,
    requestDate: new Date("2023-11-18"),
  },
  {
    id: "REQ-003",
    name: "Mike Johnson",
    email: "mike@example.com",
    phone: "+1122334455",
    accountNumber: "A00456789",
    operationType: "documentation-request",
    status: "rejected" as const,
    accountManager: "Carol Davis",
    rejectionReason: "Incomplete documentation provided",
    requestDate: new Date("2023-11-20"),
  },
  {
    id: "REQ-004",
    name: "Sarah Williams",
    email: "sarah@example.com",
    phone: "+1556677889",
    accountNumber: "A00456123",
    operationType: "profile",
    status: "pending" as const,
    accountManager: "David Wilson",
    rejectionReason: null,
    requestDate: new Date("2023-11-22"),
  },
  {
    id: "REQ-005",
    name: "Alex Brown",
    email: "alex@example.com",
    phone: "+1778899001",
    accountNumber: "A00789123",
    operationType: "create-account",
    status: "approved" as const,
    accountManager: "Emma Lee",
    rejectionReason: null,
    requestDate: new Date("2023-11-25"),
  },
  {
    id: "REQ-006",
    name: "Michael Brown",
    email: "michael@example.com",
    phone: "+1889900112",
    accountNumber: "A00321654",
    operationType: "documentation-request",
    status: "pending" as const,
    accountManager: "Fiona Chen",
    rejectionReason: null,
    requestDate: new Date("2023-11-27"),
  },
  {
    id: "REQ-007",
    name: "Olivia Davis",
    email: "olivia@example.com",
    phone: "+1990011223",
    accountNumber: "A00654987",
    operationType: "change-password",
    status: "rejected" as const,
    accountManager: "George White",
    rejectionReason: "Insufficient proof of identity",
    requestDate: new Date("2023-11-28"),
  },
  {
    id: "REQ-008",
    name: "William Taylor",
    email: "william@example.com",
    phone: "+1234567890",
    accountNumber: "A00147258",
    operationType: "create-account",
    status: "approved" as const,
    accountManager: "Henry Smith",
    rejectionReason: null,
    requestDate: new Date("2023-11-30"),
  },
  {
    id: "REQ-009",
    name: "Sophia Martinez",
    email: "sophia@example.com",
    phone: "+1345678901",
    accountNumber: "A00258369",
    operationType: "profile",
    status: "pending" as const,
    accountManager: "Isabella Wang",
    rejectionReason: null,
    requestDate: new Date("2023-12-01"),
  },
  {
    id: "REQ-010",
    name: "James Wilson",
    email: "james@example.com",
    phone: "+1456789012",
    accountNumber: "A00369147",
    operationType: "documentation-request",
    status: "approved" as const,
    accountManager: "Jack Brown",
    rejectionReason: null,
    requestDate: new Date("2023-12-02"),
  },
  {
    id: "REQ-011",
    name: "Emma Anderson",
    email: "emma@example.com",
    phone: "+1567890123",
    accountNumber: "A00741852",
    operationType: "change-password",
    status: "rejected" as const,
    accountManager: "Kevin Lee",
    rejectionReason: "Verification failed",
    requestDate: new Date("2023-12-03"),
  },
  {
    id: "REQ-012",
    name: "Lucas Garcia",
    email: "lucas@example.com",
    phone: "+1678901234",
    accountNumber: "A00852963",
    operationType: "profile",
    status: "pending" as const,
    accountManager: "Lily Chen",
    rejectionReason: null,
    requestDate: new Date("2023-12-04"),
  },
];
