import { Home, Users, File, Stars, Settings } from "lucide-react";

export const NAME_PROJECT = "Apc Prime";
export const MAX_AGE_ACCESS_TOKEN = 30 * 24 * 60 * 60;
export const MAX_AGE_REFRESH_TOKEN = 30 * 24 * 60 * 60;
export const DEFAULT_PATH = "/";
export const AUTH_LOGIN_REDIRECT = "/auth/login";
export const AUTH_DEFAULT_REDIRECT = "/auth/login";

export const ROLES = [
  { id: "1", name: "Admin" },
  { id: "2", name: "User" },
  { id: "3", name: "Manager" },
  { id: "4", name: "Guest" },
];
export const ROUTES = [
  {
    title: "Home",
    url: "/",
    items: [],
    icon: Home,
    disabled: false,
  },
  {
    title: "Users",
    url: "/users",
    items: [],
    icon: Users,
    disabled: false,
  },
  // {
  //   title: "Requests",
  //   url: "/requests",
  //   items: [],
  //   icon: File,
  //   disabled: true,
  // },
  // {
  //   title: "Transactions",
  //   url: "/transactions",
  //   icon: File,
  //   items: [],
  //   disabled: true,
  // },
  // {
  //   title: "Kyc files",
  //   url: "/kyc-files",
  //   items: [],
  //   icon: Stars,
  //   disabled: true,
  // },
  // {
  //   title: "Settings",
  //   url: "/settings",
  //   items: [
  //     {
  //       title: "Translation",
  //       url: "/translation",
  //     },
  //     {
  //       title: "Operations",
  //       url: "/operations",
  //     },
  //     {
  //       title: "Admins",
  //       url: "/admins",
  //     },
  //   ],
  //   icon: Settings,
  //   disabled: true,
  // },
];

export const mockRequests = [
  {
    id: "REQ-001",
    name: "John Doe",
    email: "john@example.com",
    phone: "+1234567890",
    accountNumber: "A00123456",
    operationType: "create-account",
    status: "pending" as const,
    accountManager: "Alice Smith",
    rejectionReason: null,
    requestDate: new Date("2023-11-15"),
  },
  {
    id: "REQ-002",
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "+1987654321",
    accountNumber: "A00987654",
    operationType: "change-password",
    status: "approved" as const,
    accountManager: "Bob Johnson",
    rejectionReason: null,
    requestDate: new Date("2023-11-18"),
  },
  {
    id: "REQ-003",
    name: "Mike Johnson",
    email: "mike@example.com",
    phone: "+1122334455",
    accountNumber: "A00456789",
    operationType: "documentation-request",
    status: "rejected" as const,
    accountManager: "Carol Davis",
    rejectionReason: "Incomplete documentation provided",
    requestDate: new Date("2023-11-20"),
  },
  {
    id: "REQ-004",
    name: "Sarah Williams",
    email: "sarah@example.com",
    phone: "+1556677889",
    accountNumber: "A00456123",
    operationType: "profile",
    status: "pending" as const,
    accountManager: "David Wilson",
    rejectionReason: null,
    requestDate: new Date("2023-11-22"),
  },
  {
    id: "REQ-005",
    name: "Alex Brown",
    email: "alex@example.com",
    phone: "+1778899001",
    accountNumber: "A00789123",
    operationType: "create-account",
    status: "approved" as const,
    accountManager: "Emma Lee",
    rejectionReason: null,
    requestDate: new Date("2023-11-25"),
  },
  {
    id: "REQ-006",
    name: "Michael Brown",
    email: "michael@example.com",
    phone: "+1889900112",
    accountNumber: "A00321654",
    operationType: "documentation-request",
    status: "pending" as const,
    accountManager: "Fiona Chen",
    rejectionReason: null,
    requestDate: new Date("2023-11-27"),
  },
  {
    id: "REQ-007",
    name: "Olivia Davis",
    email: "olivia@example.com",
    phone: "+1990011223",
    accountNumber: "A00654987",
    operationType: "change-password",
    status: "rejected" as const,
    accountManager: "George White",
    rejectionReason: "Insufficient proof of identity",
    requestDate: new Date("2023-11-28"),
  },
  {
    id: "REQ-008",
    name: "William Taylor",
    email: "william@example.com",
    phone: "+1234567890",
    accountNumber: "A00147258",
    operationType: "create-account",
    status: "approved" as const,
    accountManager: "Henry Smith",
    rejectionReason: null,
    requestDate: new Date("2023-11-30"),
  },
  {
    id: "REQ-009",
    name: "Sophia Martinez",
    email: "sophia@example.com",
    phone: "+1345678901",
    accountNumber: "A00258369",
    operationType: "profile",
    status: "pending" as const,
    accountManager: "Isabella Wang",
    rejectionReason: null,
    requestDate: new Date("2023-12-01"),
  },
  {
    id: "REQ-010",
    name: "James Wilson",
    email: "james@example.com",
    phone: "+1456789012",
    accountNumber: "A00369147",
    operationType: "documentation-request",
    status: "approved" as const,
    accountManager: "Jack Brown",
    rejectionReason: null,
    requestDate: new Date("2023-12-02"),
  },
  {
    id: "REQ-011",
    name: "Emma Anderson",
    email: "emma@example.com",
    phone: "+1567890123",
    accountNumber: "A00741852",
    operationType: "change-password",
    status: "rejected" as const,
    accountManager: "Kevin Lee",
    rejectionReason: "Verification failed",
    requestDate: new Date("2023-12-03"),
  },
  {
    id: "REQ-012",
    name: "Lucas Garcia",
    email: "lucas@example.com",
    phone: "+1678901234",
    accountNumber: "A00852963",
    operationType: "profile",
    status: "pending" as const,
    accountManager: "Lily Chen",
    rejectionReason: null,
    requestDate: new Date("2023-12-04"),
  },
];

export const mockTransactions = [
  {
    id: "tr001",
    processId: "PT001",
    date: new Date(2023, 9, 15),
    name: "John Doe",
    phoneNumber: "+1234567890",
    accountNumber: "ACC123456789",
    amount: 1500,
    withdrawalMethod: "Bank Transfer",
    address: "123 Main St, New York, NY 10001",
    status: "approved",
    rejectionReason: null,
  },
  {
    id: "tr002",
    processId: "PT002",
    date: new Date(2023, 9, 16),
    name: "Jane Smith",
    phoneNumber: "+1987654321",
    accountNumber: "ACC987654321",
    amount: 2500,
    withdrawalMethod: "Cash",
    address: null,
    status: "pending",
    rejectionReason: null,
  },
  {
    id: "tr003",
    processId: "PT003",
    date: new Date(2023, 9, 17),
    name: "Michael Johnson",
    phoneNumber: "+1122334455",
    accountNumber: "ACC112233445",
    amount: 3200,
    withdrawalMethod: "Bank Transfer",
    address: "456 Park Ave, Boston, MA 02115",
    status: "rejected",
    rejectionReason: "Insufficient funds",
  },
  {
    id: "tr004",
    processId: "PT004",
    date: new Date(2023, 9, 18),
    name: "Sarah Williams",
    phoneNumber: "+1555666777",
    accountNumber: "ACC555666777",
    amount: 800,
    withdrawalMethod: "Cash",
    address: null,
    status: "approved",
    rejectionReason: null,
  },
  {
    id: "tr005",
    processId: "PT005",
    date: new Date(2023, 9, 19),
    name: "David Brown",
    phoneNumber: "+1999888777",
    accountNumber: "ACC999888777",
    amount: 1200,
    withdrawalMethod: "Bank Transfer",
    address: "789 Oak St, Chicago, IL 60601",
    status: "pending",
    rejectionReason: null,
  },
];

export const mockKycFiles = [
  {
    id: "kyc001",
    name: "John Doe",
    accountId: "ACC123456789",
    type: "ID Card",
    dateTime: new Date(2023, 9, 15),
    procedures: "KYC verification",
    status: "approved",
    rejectionReason: null,
  },
  {
    id: "kyc002",
    name: "Jane Smith",
    accountId: "ACC987654321",
    type: "Passport",
    dateTime: new Date(2023, 9, 16),
    procedures: "Identity verification",
    status: "pending",
    rejectionReason: null,
  },
  {
    id: "kyc003",
    name: "Michael Johnson",
    accountId: "ACC112233445",
    type: "Driving License",
    dateTime: new Date(2023, 9, 17),
    procedures: "Address verification",
    status: "rejected",
    rejectionReason: "Document expired",
  },
  {
    id: "kyc004",
    name: "Sarah Williams",
    accountId: "ACC555666777",
    type: "Utility Bill",
    dateTime: new Date(2023, 9, 18),
    procedures: "Address verification",
    status: "approved",
    rejectionReason: null,
  },
  {
    id: "kyc005",
    name: "David Brown",
    accountId: "ACC999888777",
    type: "Bank Statement",
    dateTime: new Date(2023, 9, 19),
    procedures: "Financial verification",
    status: "pending",
    rejectionReason: null,
  },
];
