export enum ModalType {
  ADD_USER = "ADD_USER",
  EDIT_USER = "EDIT_USER",
  EXPORT_USER = "EXPORT_USER",
  ADD_REQUEST = "ADD_REQUEST",
  EDIT_REQUEST = "EDIT_REQUEST",
  APPROVE_REQUEST = "APPROVE_REQUEST",
  REJECT_REQUEST = "REJECT_REQUEST",
  EXPORT_REQUEST = "EXPORT_REQUEST",
  ADD_TRANSACTION = "ADD_TRANSACTION",
  EDIT_TRANSACTION = "EDIT_TRANSACTION",
  APPROVE_TRANSACTION = "APPROVE_TRANSACTION",
  REJECT_TRANSACTION = "REJECT_TRANSACTION",
  EXPORT_TRANSACTION = "EXPORT_TRANSACTION",
  ADD_KYC_FILE = "ADD_KYC_FILE",
  EDIT_KYC_FILE = "EDIT_KYC_FILE",
  VIEW_KYC_FILE = "VIEW_KYC_FILE",
  APPROVE_KYC_FILE = "APPROVE_KYC_FILE",
  REJECT_KYC_FILE = "REJECT_KYC_FILE",
  EXPORT_KYC_FILE = "EXPORT_KYC_FILE",
  LOGOUT = "LOGOUT",
  DELETE_USER = "DELETE_USER",
  BLOCK_USER = "BLOCK_USER",
  DELETE_MULTIPLE_USERS = "DELETE_MULTIPLE_USERS",
  BLOCK_MULTIPLE_USERS = "BLOCK_MULTIPLE_USERS",
  DELETE_DEVICE = "DELETE_DEVICE",
  SET_MAIN_DEVICE = "SET_MAIN_DEVICE",
  ACCEPT_DEVICE = "ACCEPT_DEVICE",
  ADD_WALLET = "ADD_WALLET",
  ADD_ACCOUNT = "ADD_ACCOUNT",
}

export enum UserRole {
  ADMIN = "admin",
  MANAGER = "manager",
  USER = "user",
  GUEST = "guest",
}

export enum UserStatus {
  ACTIVE = "active",
  INACTIVE = "inactive",
  BLOCKED = "blocked",
  PENDING = "pending",
}

export enum RequestStatus {
  PENDING = "pending",
  APPROVED = "approved",
  REJECTED = "rejected",
}
